<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "book".
 *
 * @property string $id
 * @property string $name
 * @property string $cover
 * @property string $desc
 * @property string $author
 * @property string $type
 * @property integer $status
 * @property integer $is_shelve
 * @property string $chapter_num
 * @property string $chapter_name
 * @property string $words_num
 * @property string $price
 * @property integer $sale_model
 * @property string $subcribe_num
 * @property string $click_num
 * @property string $collection_num
 * @property integer $is_agent
 * @property string $created
 * @property string $updated
 */
class Book extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'book';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'author'], 'required'],
            [['status', 'is_shelve', 'chapter_num', 'sale_model', 'subcribe_num', 'click_num', 'collection_num', 'is_agent', 'type'], 'integer'],
            [['words_num', 'price'], 'number'],
            [['created', 'updated'], 'safe'],
            [['name', 'author', 'chapter_name'], 'string', 'max' => 20],
            [['cover', 'desc'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', '书籍ID'),
            'name' => Yii::t('app', '书名'),
            'cover' => Yii::t('app', '封面'),
            'desc' => Yii::t('app', '简介'),
            'author' => Yii::t('app', '作者'),
            'type' => Yii::t('app', '类别（1：男频2：女频）'),
            'status' => Yii::t('app', '1：完结2：连载'),
            'is_shelve' => Yii::t('app', '1：上架2：下架3:删除'),
            'chapter_num' => Yii::t('app', '章节总数'),
            'chapter_name' => Yii::t('app', '最新章节名称'),
            'words_num' => Yii::t('app', '目前文字总数'),
            'price' => Yii::t('app', '书籍价格'),
            'sale_model' => Yii::t('app', '销售模式（1：章节2：整本）'),
            'subcribe_num' => Yii::t('app', '订阅数量'),
            'click_num' => Yii::t('app', '点击数量'),
            'collection_num' => Yii::t('app', '收藏数量'),
            'is_agent' => Yii::t('app', '是否分销书籍（0：否1：是）'),
            'created' => Yii::t('app', 'Created'),
            'updated' => Yii::t('app', 'Updated'),
        ];
    }

    /**
     * 获取列表
     * .
     */
    public static function items(){
        $res_data = array();
        $modles = self::find()->orderBy('id asc')->all();
        foreach ($modles as $model) {
            $res_data[$model->id] = $model->name;
        }
        return $res_data;
    }
    /**
     * 获取指定值
     * .
     */
    public static function item($id){
        if ($id){
            $name = self::find()->where(['id' =>$id]) ->asArray() ->one();
            return $name['name'];
        }
        return false;
    }


    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created = date('Y-m-d H:i:s',time());
        }
        $this->updated = date('Y-m-d H:i:s',time());
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
