<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "book_agent".
 *
 * @property string $id
 * @property string $book_id
 * @property integer $status
 * @property string $created
 * @property string $updated
 */
class BookAgent extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'book_agent';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['book_id', 'status'], 'integer'],
            [['created', 'updated'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'book_id' => Yii::t('app', '书籍ID'),
            'status' => Yii::t('app', '书籍状态（1：上架2：下架3：删除）'),
            'created' => Yii::t('app', 'Created'),
            'updated' => Yii::t('app', 'Updated'),
        ];
    }

    public static function getCreated($book_id){
        $model = self::findOne(['book_id' => $book_id]);
        if ($model)
            return $model->created;
        return false;
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created = date('Y-m-d H:i:s',time());
        }
        $this->updated = date('Y-m-d H:i:s',time());
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
