<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "category".
 *
 * @property string $id
 * @property integer $type
 * @property string $name
 * @property string $created
 * @property string $updated
 */
class Category extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type'], 'integer'],
            [['created', 'updated'], 'safe'],
            [['name'], 'string', 'max' => 20],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', '书籍分类ID'),
            'type' => Yii::t('app', '类型（1：书籍）'),
            'name' => Yii::t('app', '分类名称'),
            'created' => Yii::t('app', 'Created'),
            'updated' => Yii::t('app', 'Updated'),
        ];
    }

    /**
     * 获取列表
     * .
     */
    public static function items($type){
        $res_data = array();
        $models = self::find()->where(['type' => $type])->orderBy('id asc')->all();
        foreach ($models as $model) {
            $res_data[$model->id] = $model->name;
        }
        return $res_data;
    }

    /**
     * 获取指定值
     * .
     */
    public static function item($id){
        if ($id){
            $name = self::find()->where(['id' =>$id]) ->asArray() ->one();
            return $name['name'];
        }
        return false;
    }


    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created = date('Y-m-d H:i:s',time());
        }
        $this->updated = date('Y-m-d H:i:s',time());
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
