<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "department".
 *
 * @property string $id
 * @property string $fid
 * @property string $name
 * @property string $created
 * @property string $updated
 */
class Department extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'department';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fid'], 'integer'],
            [['name'], 'required'],
            [['created', 'updated'], 'safe'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', '部门ID'),
            'fid' => Yii::t('app', '上级ID'),
            'name' => Yii::t('app', '部门名称'),
            'created' => Yii::t('app', 'Created'),
            'updated' => Yii::t('app', 'Updated'),
        ];
    }

    public function getItem()
    {
//        return self::findAll(['index'=> 'id']);
        return self::find()->indexBy('id')->asArray()->all();
    }

    //获取所有顶级分类
    public static function getTop() {
        $items  = [
            0 => '根部门',
        ];
        $result = self::find()->where(['fid'=>0])->asArray()->all();

        if($result) {
            foreach ($result as $value) {
                $items[$value['id']] = $value['name'];
            }
        }

        return $items;
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created = date('Y-m-d H:i:s',time());
        }
        $this->updated = date('Y-m-d H:i:s',time());
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
